### PR TITLE
made directory depth configurable

### PR DESCRIPTION
**Pull request by bitboxer**
This is a first implementation to make the directory depth configurable. Please comment what you like/dislike. Will try to improve till you like it 😉

### CODE REVIEW

**Comment by lukech** [comment]
Hey, it's great to have dir depth configurable, but would it be better setting default to check to the 'bottom', instead of 1 level depth, and what's the point to hardcode MAXDEPTH :)

**Comment by bitboxer** [comment]
Sorry, don't understand what you mean. Can you explain it in more detail? Thanks!

**Comment by lukech** [comment]
I can see you set default directory depth to 2, just suggest making the default depth to 'max' i.e. search all sub directories no matter how deep they are (if -m is not specified in the command). Actually I submitted another pull request for that today :)

**Comment by bitboxer** [comment]
I did that on purpose to keep the old behavior and not break that

**Comment by kamranahmedse** [comment]
@bitboxer thanks for the PR but it doesn't seem to be working 

Demo

**Comment by bitboxer** [comment]
Hm...interesting. Let me try to figure out what is wrong there . What directories do you have in your `/Users` directory? What is 11.27.45?

**Comment by bitboxer** [comment]
(And sorry for the late reply, I am on vacation right now ☀️ )

**Comment by kamranahmedse** [comment]
Not sure, where it picked that up. There is nothing like this in there.

**Comment by bitboxer** [comment]
Hm...strange. What happens if you do `find . -name .git -type d -maxdepth 2` in that directory? Do you see that 11.27.24 there?

**Comment by kamranahmedse** [comment]
Nope.

**Comment by bitboxer** [comment]
And it still happens?

**Comment by kamranahmedse** [comment]
Strange but yes. Here http://i.imgur.com/YRKQEry.png

**Comment by kamranahmedse** [comment]
Wait. I guess, I found the cause. Seems like some repositories in my trash were causing it.
```
./.Trash/ikes 11.27.45 PM/.git
```
- Can you make it not look into my trash
- Plus it doesn't seem to be working when you have spaces in the project directory name.

**Comment by bitboxer** [comment]
Yes, I should do the spaces thing. But I don't wanna exclude directories as default in there. That could lead to problems.

**Comment by kamranahmedse** [comment]
Okay fine. Fix the spaces issue and we are good here.

**Comment by bitboxer** [comment]
@kamranahmedse can you check if the whitespace issue is resolved? If yes, I will rebase this to the current master.

**Comment by kamranahmedse** [comment]
Yes it seems to be working fine now.

**Comment by bitboxer** [comment]
Perfect. It is now rebased.

**Comment by kamranahmedse** [comment]
Cool. Thanks :)

**Pull request merged**
