### PR TITLE
Show branch names and tags

### PR DESCRIPTION
**Pull request by darrarski**
I would like to see branch names and tags for each commit in the output.

Adding `%d` to `git log`'s `--pretty=format:` parameter gives us tags and branch names printed. 

Unfortunately, this is not a perfect solution, as it won't display branch name unless the commit is the last one on the branch. Not sure how could it be solved, or even if it's possible without massive changes in the project.

Any hints on how to improve this will be appreciated.

### CODE REVIEW

**Comment by kwiersma** [comment]
Thanks this is really helpful!

**Comment by kamranahmedse** [comment]
@darrarski thanks for taking the time to create the PR but showing branch against only one commit isn't going to cut it out. And for adding the branch name against each of the commit is going to require the utility to be rewritten from the ground up, so I think it is fine without it. 

But thanks though :)

**Comment by olivergierke** [comment]
I don't quite get the response. It would be extremely helpful to see the branch a particular commit was made on, especially when working with cherry-picks and backports. The PR would just have achieved that. What's wrong with it?

**Comment by kamranahmedse** [comment]
@olivergierke I closed it because this would show the branch name against the last commit only and won't show the branch names against the rest of them.
On second thoughts, it won't hurt

**Comment by kamranahmedse** [comment]
@olivergierke I closed it because this would show the branch name only if the commit in the "standup commits" is the last commit of the branch and won't show the branch names otherwise.

But anyways, on second thoughts, it won't hurt so merging. Thanks @darrarski

**Comment by olivergierke** [comment]
I was under the impression that the change would tweak the output for every commit rendered. Maybe allowing to configure the pattern to format the lines to print for each commit is even more flexible.

Thanks for giving this a second thought, though! 🙃👍

**Pull request merged**
